### ISSUE TITLE
make / make test fails with new go version 1.21

### ISSUE THREAD

**Issue by brandonm78** [axieinfinity/ronin#345]
#### System information

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
go version go1.21.0 linux/amd64

Repeated on second machine running:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
go version go1.21.0 linux/amd64

#### Expected behaviour

make ronin & make test would complete without issues.

#### Actual behaviour  (immediately proceeding lines leading up to the failure during make test command)

github.com/ethereum/go-ethereum/internal/jsre
# github.com/pyroscope-io/godeltaprof/internal/pprof
/root/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/root/go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
github.com/naoina/toml
github.com/ethereum/go-ethereum/console
util.go:46: exit status 1
exit status 1
make: *** [Makefile:40: all] Error 1

#### Steps to reproduce the behaviour

Install go version 1.21 and run make test.  Afterwards:  I then downgraded to version 1.20.7 and make ronin / make test completed properly as it had prior to go version 1.21 being installed.

**Comment by minh-bq** [comment]
Thanks for your report. This should be fixed in https://github.com/axieinfinity/ronin/pull/346.
