### ISSUE TITLE
Ronin Archival Snapshot

### ISSUE THREAD

**Issue by shaswatsaloni** [axieinfinity/ronin#428]
Hi All,
Can anyone provide me the link to download an archival snapshot for mainnet starting from Block 1.

Thanks,
Saloni

**Comment by shaswatsaloni** [comment]
okay got it, but do we need to download all the files for it to get the data from block 0?

**Comment by minh-bq** [comment]
yes, you need to download all the files.

**Comment by shaswatsaloni** [comment]
Hi, @minh-bq , i downloaded the prerequisite that is **zstd**, provided **8tb of disk size** and tried to download only the first file. 

_Command used:_ 
![image](https://github.com/axieinfinity/ronin/assets/132393582/5c4fc96a-228e-49f0-baad-948db8fafdb7)

But running into some **error** after it downloaded around **117GB** of files. Attaching the screenshot of the error here:

![image](https://github.com/axieinfinity/ronin/assets/132393582/7c76ff49-fb23-482e-8f19-76864cfda02b)

Could you please help me with this?

Thanks,
Saloni.

**Comment by minh-bq** [comment]
According to the guide in README, I believe that you must download all the files and concatenate them before decompressing.

**Comment by shaswatsaloni** [comment]
ok, @minh-bq  i tried only one command at a time which is:

wget -O chaindata.tar.zst  "https://ss.roninchain.com/archive-mainnet-chaindata-20240306.tar.zst-000"

but still after 18% completion, got this error.

![image](https://github.com/axieinfinity/ronin/assets/132393582/090a3bd2-25ae-4a83-b3f4-5781509c09eb)

Could you please help me with this?

Thanks,
Saloni.

**Comment by minh-bq** [comment]
This might be because of unusual network error between your local and server. Normally, wget will disconnect or have a limit times to retry.
You can try to add these flag to your command `--retry-connrefused` (retry) and `--continue` (to keep download from the last byte), `--tries=0`  (for infinite retry, default is 20 times). For example:
```
wget --retry-connrefused --continue --tries=0 -O chaindata.tar.zst "https://ss.roninchain.com/archive-mainnet-chaindata-20240306.tar.zst-000"
```
Reference: https://linux.die.net/man/1/wget

**Comment by shaswatsaloni** [comment]
Hi, @minh-bq , I tried the above command. But it is **stuck at 3%** from around 4-5 hours. 

Attaching screenshot:
![image](https://github.com/axieinfinity/ronin/assets/132393582/d883b29f-eed9-4b23-8f22-5b6499341600)

And one more quick question: I am using **ubuntu 18.04**, will it be enough or we need ubuntu **20.04 or 22.04**?

Thanks,
Saloni.

**Comment by shaswatsaloni** [comment]
Checking on this again? Can anyone help me with this?

**Comment by minh-bq** [comment]
Hi, can you retry (Ctrl+C then run command again)? It should start from where it is left off not from 0%.

**Comment by tudoanm** [comment]
First of all, I have thought that you used a mistaken section of the docs for this download chaindata snapshot.
<img width="985" alt="image" src="https://github.com/axieinfinity/ronin/assets/139109879/3c051e56-311c-47b3-a95b-c2d4451de41f">
☝️  Above is the correct part, which at the end of README. The script is for downloading 13 different files. It also means that, the `-O chaindata.tar.zst` in your command is not correct. It should be `-O chaindata.tar.zst-00X` (X is the index of each file). Cause you will need to combine those files later.  

Secondly, I think that the scripts is just an example of usage. So don't forget to custom the wget command in script to get a retry as minh-bq has mentioned, `--retry-connrefused --continue --tries=0` . Despite any error from networks (like in your case), you can cancel the download any time and re-enter the command, it will successfully continue to download.
Hope this help!

**Comment by shaswatsaloni** [comment]
Hi, thanks for this, one more thing.
Do i need to put all files to download at once or can i try with only one file to see if that works for me?

**Comment by minh-bq** [comment]
Currently, you have to download all files, concatenate them then decompress. We'll try to improve that in the future.

**Comment by tudoanm** [comment]
If i am not wrong, you are asking whether to download them all at once or one by one ? If so, yes, you could download one by one, but notice the file name to not overwrite the downloaded file by the new one.
However, when decompressing, all of the files must be concatenated at the same time.

**Comment by shaswatsaloni** [comment]
Hi, I am able to download all the tar files, now working on untar. Thats why still this ticket is opened. Once that is done. I will close this.

Thanks,
Saloni

**Comment by shaswatsaloni** [comment]
Hi @minh-bq , i downloaded the tar files that was completed. But while doing the untar it with the command:

**tar -I zstd -xvf chaindata.tar.zst**

The size that is there is around 7TB. It ran for 24 hours, but in the end it says something like this:

![image](https://github.com/axieinfinity/ronin/assets/132393582/80fef482-a909-4842-93cd-d506f3c963e4)

What does this mean? Or should i proceed to run the node on top of this?

Thanks.
Saloni

**Comment by minh-bq** [comment]
Close as it seems to be resolved. Feel free to re-open if the problem still exists.
