### ISSUE TITLE
Node synching failed

### ISSUE THREAD

**Issue by shaswatsaloni** [axieinfinity/ronin#483]
Node synching failed:

Getting error as : Snapshot extension registration failed for ronin.

![image](https://github.com/axieinfinity/ronin/assets/132393582/c03ddc17-7546-49d2-a956-c985b3496741)

Can anyone help me with this?

Thanks,
Saloni.

**Comment by minh-bq** [comment]
Could you upload the full log? Which version of Ronin do you use?
That log line is just for information and safe to ignore.

**Comment by shaswatsaloni** [comment]
Hi @minh-bq , thanks for getting back this fast.

Node is not synching as of now.

Node details:
we are running an archival node with snapshot approach.

Github link to download the snapshot:
https://github.com/axieinfinity/ronin-snapshot 

Commands we performed:

for i in {000..013}; do wget "https://ss.roninchain.com/archive-mainnet-chaindata-20240306.tar.zst-$i "; done
cat "archive-mainnet-chaindata-20240306.tar.zst-"* > chaindata.tar.zst
tar -I zstd -xvf chaindata.tar.zst

Docker-compose looks like this:

![image](https://github.com/axieinfinity/ronin/assets/132393582/50430a32-83b7-4763-b820-cccf254aed51)

Thanks,
Saloni.

**Comment by minh-bq** [comment]
We've recently released a new version and it looks like your node is not upgraded so cannot sync with the network. Can you please update the NODE_IMAGE to `ghcr.io/axieinfinity/ronin:v2.8.3-d27eb42` then run `docker-compose up -d` to see if the problem resolves?

**Comment by shaswatsaloni** [comment]
Yes, that helped.

Thanks @minh-bq :)
